site_name: cappuccino2
site_description: Ayuda a la generación de Horarios para la Facultad de Ciencias y Tecnología de la Universidad Mayor de San Simón
repo_url: https://github.com/danielstp/danielstp
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/danielstp">danielstp</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
