# Generated by Django 2.1.7 on 2019-02-18 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualización',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default='2016-01-01 00:00:00-04')),
                ('fechaPDF', models.DateTimeField(default='2016-01-01 00:00:00-04')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('código', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ayudante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('código', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('pdf', models.URLField()),
                ('fecha', models.DateTimeField(default='2016-01-01 00:00:00-04')),
                ('fechaPDF', models.DateTimeField(default='2016-01-01 00:00:00-04')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('código', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=2)),
                ('ayudante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='horario.Ayudante')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='horario.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('código', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('día', models.CharField(choices=[('LU', 'LU'), ('MA', 'MA'), ('MI', 'MI'), ('JU', 'JU'), ('VI', 'VI'), ('SA', 'SA'), ('DO', 'DO')], max_length=2)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='horario.Aula')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='horario.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('código', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NivelMateria',
            fields=[
                ('código', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=1)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='horario.Carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='horario.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='horario.Materia'),
        ),
        migrations.AddField(
            model_name='actualización',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='horario.Carrera'),
        ),
    ]
