# Generated by Django 4.1.8 on 2023-04-17 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                ("código", models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                "ordering": ("código",),
            },
        ),
        migrations.CreateModel(
            name="Ayudante",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("nombre",),
            },
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                ("código", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("pdf", models.URLField()),
                ("fecha", models.DateTimeField(default="2016-01-01 00:00:00-04")),
                ("fechaPDF", models.DateTimeField(default="2016-01-01 00:00:00-04")),
            ],
            options={
                "ordering": ("nombre",),
            },
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("nombre",),
            },
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                ("código", models.CharField(max_length=25, primary_key=True, serialize=False)),
                ("grupo", models.CharField(max_length=2)),
                (
                    "ayudante",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="horario.ayudante"),
                ),
                (
                    "docente",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="horario.docente"),
                ),
            ],
            options={
                "ordering": ("grupo",),
            },
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                ("nombre", models.CharField(max_length=255)),
                ("código", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "ordering": ("nombre",),
            },
        ),
        migrations.CreateModel(
            name="NivelMateria",
            fields=[
                ("código", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("nivel", models.CharField(max_length=1)),
                ("carrera", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="horario.carrera")),
                ("materia", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="horario.materia")),
            ],
            options={
                "ordering": ("carrera", "nivel", "materia"),
            },
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                ("código", models.CharField(max_length=25, primary_key=True, serialize=False)),
                (
                    "día",
                    models.CharField(
                        choices=[
                            ("LU", "LU"),
                            ("MA", "MA"),
                            ("MI", "MI"),
                            ("JU", "JU"),
                            ("VI", "VI"),
                            ("SA", "SA"),
                            ("DO", "DO"),
                        ],
                        max_length=2,
                    ),
                ),
                ("inicio", models.TimeField()),
                ("fin", models.TimeField()),
                ("aula", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="horario.aula")),
                ("grupo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="horario.grupo")),
            ],
            options={
                "ordering": ("grupo",),
            },
        ),
        migrations.AddField(
            model_name="grupo",
            name="materia",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="horario.materia"),
        ),
        migrations.CreateModel(
            name="Actualización",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha", models.DateTimeField(default="2016-01-01 00:00:00-04")),
                ("fechaPDF", models.DateTimeField(default="2016-01-01 00:00:00-04")),
                ("carrera", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="horario.carrera")),
            ],
            options={
                "ordering": ("fecha",),
            },
        ),
    ]
