# Generated by Django 5.2.8 on 2025-11-14 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actualización",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("fecha_pdf", models.DateField(auto_now_add=True)),
                ("url_pdf", models.URLField(default="", max_length=255)),
                ("semestre", models.CharField(default="1", max_length=1)),
                ("año", models.IntegerField(default=2020)),
            ],
            options={
                "verbose_name_plural": "Actualizaciones",
                "ordering": ("fecha",),
                "indexes": [
                    models.Index(fields=["fecha"], name="horario_act_fecha_d2812f_idx"),
                    models.Index(
                        fields=["fecha_pdf"], name="horario_act_fecha_p_0aefdf_idx"
                    ),
                    models.Index(
                        fields=["semestre"], name="horario_act_semestr_3669c7_idx"
                    ),
                ],
                "unique_together": {("año", "semestre", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "código",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
            ],
            options={
                "ordering": ("código",),
                "indexes": [
                    models.Index(
                        fields=["código"], name="horario_aul_código_ce5f55_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Ayudante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("nombre",),
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="horario_ayu_nombre_45a5d7_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                ("código", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("nombre",),
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="horario_car_nombre_8042d0_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("nombre",),
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="horario_doc_nombre_ed4c3f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                ("nombre", models.CharField(max_length=255)),
                ("código", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "ordering": ("nombre",),
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="horario_mat_nombre_63db88_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "código",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("grupo", models.CharField(max_length=2)),
                (
                    "actualización",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="horario.actualización",
                    ),
                ),
                (
                    "ayudante",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="horario.ayudante",
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="horario.docente",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="horario.materia",
                    ),
                ),
            ],
            options={
                "ordering": ("grupo",),
            },
        ),
        migrations.CreateModel(
            name="NivelMateria",
            fields=[
                (
                    "código",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nivel", models.CharField(max_length=1)),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="horario.carrera",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="horario.materia",
                    ),
                ),
            ],
            options={
                "ordering": ("carrera", "nivel", "materia"),
            },
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "código",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                (
                    "día",
                    models.CharField(
                        choices=[
                            ("LU", "Monday"),
                            ("MA", "Tuesday"),
                            ("MI", "Wednesday"),
                            ("JU", "Thursday"),
                            ("VI", "Friday"),
                            ("SA", "Saturday"),
                            ("DO", "Sunday"),
                        ],
                        max_length=2,
                    ),
                ),
                ("inicio", models.TimeField()),
                ("fin", models.TimeField()),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="horario.aula"
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="horario.grupo"
                    ),
                ),
            ],
            options={
                "ordering": ("grupo",),
                "indexes": [
                    models.Index(
                        fields=["código"], name="horario_hor_código_d7bcd5_idx"
                    ),
                    models.Index(fields=["día"], name="horario_hor_día_1ae7c6_idx"),
                    models.Index(
                        fields=["inicio"], name="horario_hor_inicio_80eb95_idx"
                    ),
                    models.Index(fields=["fin"], name="horario_hor_fin_15f9f3_idx"),
                    models.Index(
                        fields=["aula"], name="horario_hor_aula_id_baa9e3_idx"
                    ),
                    models.Index(
                        fields=["grupo"], name="horario_hor_grupo_i_6d6eae_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(fields=["código"], name="horario_gru_código_e1a88c_idx"),
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(fields=["grupo"], name="horario_gru_grupo_6d35df_idx"),
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(
                fields=["materia"], name="horario_gru_materia_b0cfff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(
                fields=["docente"], name="horario_gru_docente_d477e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(
                fields=["ayudante"], name="horario_gru_ayudant_49152c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(
                fields=["actualización"], name="horario_gru_actuali_a4dce0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nivelmateria",
            index=models.Index(fields=["código"], name="horario_niv_código_35c4fb_idx"),
        ),
        migrations.AddIndex(
            model_name="nivelmateria",
            index=models.Index(
                fields=["carrera"], name="horario_niv_carrera_dbf5d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nivelmateria",
            index=models.Index(fields=["nivel"], name="horario_niv_nivel_b64a0c_idx"),
        ),
        migrations.AddIndex(
            model_name="nivelmateria",
            index=models.Index(
                fields=["materia"], name="horario_niv_materia_2b7e63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nivelmateria",
            index=models.Index(
                fields=["carrera", "nivel", "materia"],
                name="horario_niv_carrera_d7acc0_idx",
            ),
        ),
    ]
