# Generated by Django 2.2.5 on 2019-09-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualización',
            options={'ordering': ('fecha',)},
        ),
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ('código',)},
        ),
        migrations.AlterModelOptions(
            name='ayudante',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ('grupo',)},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ('grupo',)},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='nivelmateria',
            options={'ordering': ('carrera', 'nivel', 'materia')},
        ),
    ]
