# Generated by Django 5.2.7 on 2025-10-20 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horario", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actualización",
            options={"ordering": ("fecha",), "verbose_name_plural": "Actualizaciones"},
        ),
        migrations.RemoveField(
            model_name="actualización",
            name="fechaPDF",
        ),
        migrations.RemoveField(
            model_name="carrera",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="carrera",
            name="fechaPDF",
        ),
        migrations.AddField(
            model_name="actualización",
            name="fecha_pdf",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actualización",
            name="semestre",
            field=models.CharField(default="1", max_length=10),
        ),
        migrations.AddField(
            model_name="grupo",
            name="actualización",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="horario.actualización",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="actualización",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
