# Generated by Django 5.2.8 on 2025-11-25 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gestión",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("año", models.IntegerField()),
                ("semestre", models.CharField(max_length=1)),
                ("inicio", models.DateField()),
                ("fin", models.DateField()),
            ],
            options={
                "verbose_name_plural": "Gestiones",
                "ordering": ("año", "semestre"),
            },
        ),
        migrations.RemoveIndex(
            model_name="actualización",
            name="horario_act_semestr_3669c7_idx",
        ),
        migrations.AddField(
            model_name="actualización",
            name="carreras",
            field=models.ManyToManyField(to="horario.carrera"),
        ),
        migrations.AlterField(
            model_name="actualización",
            name="fecha",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="actualización",
            name="fecha_pdf",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="actualización",
            name="id",
            field=models.CharField(
                editable=False, max_length=30, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="gestión",
            index=models.Index(fields=["año"], name="horario_ges_año_fc4d1f_idx"),
        ),
        migrations.AddIndex(
            model_name="gestión",
            index=models.Index(
                fields=["semestre"], name="horario_ges_semestr_bcc67f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gestión",
            unique_together={("año", "semestre")},
        ),
        migrations.AlterUniqueTogether(
            name="actualización",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="actualización",
            name="gestión",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="horario.gestión",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="actualización",
            unique_together={("gestión", "fecha")},
        ),
        migrations.AddIndex(
            model_name="actualización",
            index=models.Index(
                fields=["gestión"], name="horario_act_gestión_2c515e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actualización",
            index=models.Index(
                fields=["gestión", "fecha"], name="horario_act_gestión_1b2da7_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="actualización",
            name="año",
        ),
        migrations.RemoveField(
            model_name="actualización",
            name="semestre",
        ),
    ]
