# Generated by Django 5.2.8 on 2025-11-25 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horario", "0002_gestión_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="ayudante",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="horario.ayudante",
            ),
        ),
    ]
