# Generated by Django 5.2.7 on 2025-10-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horario", "0002_alter_actualización_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horario",
            name="día",
            field=models.CharField(
                choices=[
                    ("LU", "Monday"),
                    ("MA", "Tuesday"),
                    ("MI", "Wednesday"),
                    ("JU", "Thursday"),
                    ("VI", "Friday"),
                    ("SA", "Saturday"),
                    ("DO", "Sunday"),
                ],
                max_length=2,
            ),
        ),
        migrations.AddIndex(
            model_name="actualización",
            index=models.Index(fields=["fecha"], name="horario_act_fecha_d2812f_idx"),
        ),
        migrations.AddIndex(
            model_name="actualización",
            index=models.Index(
                fields=["fecha_pdf"], name="horario_act_fecha_p_0aefdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actualización",
            index=models.Index(
                fields=["semestre"], name="horario_act_semestr_3669c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aula",
            index=models.Index(fields=["código"], name="horario_aul_código_ce5f55_idx"),
        ),
        migrations.AddIndex(
            model_name="ayudante",
            index=models.Index(fields=["nombre"], name="horario_ayu_nombre_45a5d7_idx"),
        ),
        migrations.AddIndex(
            model_name="carrera",
            index=models.Index(fields=["nombre"], name="horario_car_nombre_8042d0_idx"),
        ),
        migrations.AddIndex(
            model_name="docente",
            index=models.Index(fields=["nombre"], name="horario_doc_nombre_ed4c3f_idx"),
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(fields=["código"], name="horario_gru_código_e1a88c_idx"),
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(fields=["grupo"], name="horario_gru_grupo_6d35df_idx"),
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(
                fields=["materia"], name="horario_gru_materia_b0cfff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(
                fields=["docente"], name="horario_gru_docente_d477e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(
                fields=["ayudante"], name="horario_gru_ayudant_49152c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grupo",
            index=models.Index(
                fields=["actualización"], name="horario_gru_actuali_a4dce0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horario",
            index=models.Index(fields=["código"], name="horario_hor_código_d7bcd5_idx"),
        ),
        migrations.AddIndex(
            model_name="horario",
            index=models.Index(fields=["día"], name="horario_hor_día_1ae7c6_idx"),
        ),
        migrations.AddIndex(
            model_name="horario",
            index=models.Index(fields=["inicio"], name="horario_hor_inicio_80eb95_idx"),
        ),
        migrations.AddIndex(
            model_name="horario",
            index=models.Index(fields=["fin"], name="horario_hor_fin_15f9f3_idx"),
        ),
        migrations.AddIndex(
            model_name="horario",
            index=models.Index(fields=["aula"], name="horario_hor_aula_id_baa9e3_idx"),
        ),
        migrations.AddIndex(
            model_name="horario",
            index=models.Index(fields=["grupo"], name="horario_hor_grupo_i_6d6eae_idx"),
        ),
        migrations.AddIndex(
            model_name="materia",
            index=models.Index(fields=["nombre"], name="horario_mat_nombre_63db88_idx"),
        ),
        migrations.AddIndex(
            model_name="nivelmateria",
            index=models.Index(fields=["código"], name="horario_niv_código_35c4fb_idx"),
        ),
        migrations.AddIndex(
            model_name="nivelmateria",
            index=models.Index(
                fields=["carrera"], name="horario_niv_carrera_dbf5d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nivelmateria",
            index=models.Index(fields=["nivel"], name="horario_niv_nivel_b64a0c_idx"),
        ),
        migrations.AddIndex(
            model_name="nivelmateria",
            index=models.Index(
                fields=["materia"], name="horario_niv_materia_2b7e63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nivelmateria",
            index=models.Index(
                fields=["carrera", "nivel", "materia"],
                name="horario_niv_carrera_d7acc0_idx",
            ),
        ),
    ]
