# Generated by Django 5.2.8 on 2025-11-25 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horario", "0003_alter_grupo_ayudante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="ayudante",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="horario.ayudante",
            ),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="código",
            field=models.CharField(
                editable=False, max_length=25, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="docente",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="horario.docente",
            ),
        ),
    ]
