# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0004_auto_20170207_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='id',
        ),
        migrations.AddField(
            model_name='grupo',
            name='ayudante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horario.Ayudante'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horario.Docente'),
        ),
        migrations.AddField(
            model_name='horario',
            name='aula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horario.Aula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='codigo',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
