# Generated by Django 5.2.8 on 2025-11-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horario", "0004_alter_grupo_ayudante_alter_grupo_código_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualización",
            name="id",
            field=models.CharField(
                editable=False, max_length=20, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="código",
            field=models.CharField(
                editable=False, max_length=30, primary_key=True, serialize=False
            ),
        ),
    ]
