# Generated by Django 5.2.8 on 2025-11-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horario", "0005_alter_actualización_id_alter_grupo_código"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="código",
            field=models.CharField(
                editable=False, max_length=32, primary_key=True, serialize=False
            ),
        ),
    ]
