# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0005_auto_20170207_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horario.Grupo'),
            preserve_default=False,
        ),
    ]
