# Generated by Django 5.2.8 on 2025-12-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0006_alter_grupo_código'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='código',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
