# Generated by Django 5.2.8 on 2025-12-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0007_alter_horario_código'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ('grupo', 'aula', 'día', 'inicio', 'fin')},
        ),
        migrations.RemoveIndex(
            model_name='horario',
            name='horario_hor_inicio_80eb95_idx',
        ),
        migrations.RemoveIndex(
            model_name='horario',
            name='horario_hor_fin_15f9f3_idx',
        ),
        migrations.AlterField(
            model_name='ayudante',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['día', 'aula'], name='horario_hor_día_9433e4_idx'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['día', 'grupo'], name='horario_hor_día_83ccad_idx'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['día', 'aula', 'grupo'], name='horario_hor_día_ebd9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['día', 'aula', 'grupo', 'inicio'], name='horario_hor_día_26d335_idx'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['día', 'aula', 'grupo', 'fin'], name='horario_hor_día_b274cd_idx'),
        ),
    ]
