# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0007_auto_20170207_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='nivel',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horario',
            name='día',
            field=models.CharField(choices=[('LU', 'LU'), ('MA', 'MA'), ('MI', 'MI'),
                                            ('JU', 'JU'), ('VI', 'VI'), ('SA', 'SA'), ('DO', 'DO')], max_length=2),
        ),
    ]
