# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0008_auto_20170224_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualización',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default='2016-01-01 00:00:00-04')),
                ('fechaPDF', models.DateTimeField(default='2016-01-01 00:00:00-04')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.Carrera')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
