# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0009_auto_20170228_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelMateria',
            fields=[
                ('código', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='codigo',
            new_name='código',
        ),
        migrations.RenameField(
            model_name='carrera',
            old_name='codigo',
            new_name='código',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='codigo',
            new_name='código',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='codigo',
            new_name='código',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='codigo',
            new_name='código',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nivel',
        ),
        migrations.AddField(
            model_name='nivelmateria',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.Carrera'),
        ),
        migrations.AddField(
            model_name='nivelmateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.Materia'),
        ),
    ]
